In [3]:
import sympy as sympy
import numpy as np
import matplotlib.pyplot as plt
from scipy import *

In [4]:
x_vector = np.array([5,0,0])
print x_vector

[5 0 0]


In [5]:
c_list = [1,2]
print "The list:",c_list
print "Has length:", len(c_list)

c_vector = np.array(c_list)
print "The vector:", c_vector
print "Has shape:",c_vector.shape

The list: [1, 2]
Has length: 2
The vector: [1 2]
Has shape: (2L,)


In [6]:
z = [5,6]
print "This is a list, not an array:",z
print type(z)

This is a list, not an array: [5, 6]
<type 'list'>


In [7]:
zarray = np.array(z)
print "This is an array, not a list",zarray
print type(zarray)

This is an array, not a list [5 6]
<type 'numpy.ndarray'>


In [9]:
#Matrices

b = zip(z,c_vector)
print b
print "Note that the length of our zipped list is 2 not (2 by 2)"

[(5, 1), (6, 2)]
Note that the length of our zipped list is 2 not (2 by 2)


In [10]:
print "But we can convert the list to a matrix like this:"
A = np.array(b)
print A
print type(A)
print "A has shape:",A.shape

But we can convert the list to a matrix like this:
[[5 1]
 [6 2]]
<type 'numpy.ndarray'>
A has shape: (2L, 2L)


In [11]:
##Matrix Addition and Subtraction
result = A + 3
#or
result = 3 + A
print result

[[8 4]
 [9 5]]


In [12]:
B = np.random.randn(2,2)
print B

[[ 0.38657686  0.8254389 ]
 [-2.30137514  0.61041283]]


In [13]:
result = A + B
result

array([[5.38657686, 1.8254389 ],
       [3.69862486, 2.61041283]])

In [14]:
result = A - B
result

array([[4.61342314, 0.1745611 ],
       [8.30137514, 1.38958717]])