In [11]:
import sympy as sympy
import numpy as np
import matplotlib.pyplot as plt
from scipy import *

In [12]:
x_vector = np.array([5,0,0])
print x_vector

[5 0 0]


In [13]:
c_list = [1,2]
print "The list:",c_list
print "Has length:", len(c_list)

c_vector = np.array(c_list)
print "The vector:", c_vector
print "Has shape:",c_vector.shape

The list: [1, 2]
Has length: 2
The vector: [1 2]
Has shape: (2L,)


In [14]:
#Matrices

b = zip(z,c_vector)
print b
print "Note that the length of our zipped list is 2 not (2 by 2)"

[(5, 1), (6, 2)]
Note that the length of our zipped list is 2 not (2 by 2)


In [15]:
print "But we can convert the list to a matrix like this:"
A = np.array(b)
print A
print type(A)
print "A has shape:",A.shape

But we can convert the list to a matrix like this:
[[5 1]
 [6 2]]
<type 'numpy.ndarray'>
A has shape: (2L, 2L)


In [16]:
B = np.random.randn(2,2)
print B

[[-2.08395676  1.22678225]
 [ 0.43884417 -1.28907994]]


In [ ]:
##Matrix Multiplication

In [18]:
A * 3

array([[15,  3],
       [18,  6]])

In [19]:
##Multiplication two Matrices

In [20]:
# Redefiniendo A y C ,multiplicando AxC
A = np.arange(6).reshape((3,2))
C = np.random.randn(2,2)

print A.shape
print C.shape

(3L, 2L)
(2L, 2L)


In [23]:
print A.dot(C)
print np.dot(A,C)

[[ -1.65009392   0.58785293]
 [ -6.5347344   -0.57477231]
 [-11.41937487  -1.73739755]]
[[ -1.65009392   0.58785293]
 [ -6.5347344   -0.57477231]
 [-11.41937487  -1.73739755]]


In [27]:
##Inverse
print C

[[-0.79222632 -1.16916555]
 [-1.65009392  0.58785293]]


In [28]:
C_inverse = np.linalg.inv(C)
print C_inverse

[[-0.24545566 -0.48818044]
 [-0.68899017  0.33079096]]


In [29]:
print C.dot(C_inverse)
print "Is identical to:"
print C_inverse.dot(C)

[[ 1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00]]
Is identical to:
[[1.00000000e+00 0.00000000e+00]
 [1.11022302e-16 1.00000000e+00]]
