In [17]:
import sympy as sympy
import numpy as np
import matplotlib.pyplot as plt
from scipy import *


In [18]:
x_vector = np.array([5,0,0])
print x_vector

[5 0 0]


In [19]:
c_list = [1,2]
print "The list:",c_list
print "Has length:", len(c_list)

c_vector = np.array(c_list)
print "The vector:", c_vector
print "Has shape:",c_vector.shape

The list: [1, 2]
Has length: 2
The vector: [1 2]
Has shape: (2L,)


In [20]:
#Matrices
z = [5,6]
b = zip(z,c_vector)

In [21]:
A = np.array(b)
print A
print type(A)

[[5 1]
 [6 2]]
<type 'numpy.ndarray'>


In [7]:
B = np.random.randn(2,2)
print B

[[-0.83552849  0.53338895]
 [ 2.44059364 -1.08821259]]


In [22]:
#Transposing a Matrix
A = np.arange(6).reshape((3,2))
B = np.arange(8).reshape((2,4))
print "A is"
print A

print "The Transpose of A is"
print A.T

A is
[[0 1]
 [2 3]
 [4 5]]
The Transpose of A is
[[0 2 4]
 [1 3 5]]


In [23]:
print B.T.dot(A.T)
print "Is identical to:"
print (A.dot(B)).T

[[ 4 12 20]
 [ 5 17 29]
 [ 6 22 38]
 [ 7 27 47]]
Is identical to:
[[ 4 12 20]
 [ 5 17 29]
 [ 6 22 38]
 [ 7 27 47]]


In [11]:
R = np.array([
    [5, 3, 0, 1],
    [4, 0, 0, 1],
    [1, 1, 0, 5],
    [1, 0, 0, 4],
    [0, 1, 5, 4],
])

In [15]:
R = [
     [5,3,0,1],
     [4,0,0,1],
     [1,1,0,5],
     [1,0,0,4],
     [0,1,5,4],
    ]

R = np.array(R)

N = len(R)
M = len(R[0])
K = 2

P = np.random.rand(N,K)
Q = np.random.rand(M,K)

nP, nQ = matrix_factorization(R, P, Q, K)
nR = np.dot(nP, nQ.T)

NameError: name 'matrix_factorization' is not defined