In [2]:
import sympy as sympy
import numpy as np
import matplotlib.pyplot as plt
from scipy import *


In [3]:
x_vector = np.array([1,2,0])
print x_vector

[1 2 0]


In [6]:
x1 = [1,2,0]
x2 = [1,0,0]
x3= [3,0,1]

In [9]:
x1_vector = np.array(x1)
x2_vector = np.array(x2)
x3_vector = np.array(x3)

In [10]:
b = zip(x1,x2,x3)

In [12]:
A = np.array(b)
print A

[[1 1 3]
 [2 0 0]
 [0 0 1]]


In [13]:
y1 = [1,1,0]
y2 = [1,0,1]
y3= [4,0,0]

y1_vector = np.array(y1)
y2_vector = np.array(y2)
y3_vector = np.array(y3)

j = zip(x1,x2,x3)
B = np.array(j)
print B


[[1 1 3]
 [2 0 0]
 [0 0 1]]


In [14]:
print "The Transpose of A is"
print A.T

The Transpose of A is
[[1 2 0]
 [1 0 0]
 [3 0 1]]
