In [18]:
import sympy as sympy
import numpy as np
import matplotlib.pyplot as plt
from sympy import Matrix
from scipy import *


In [5]:
##Subspaces

x1 = [1,0,0]
x2 = [0,1,-5]
x3 = [0,0,1]

x1_vector = np.array(x1)
x2_vector = np.array(x2)
x3_vector = np.array(x3)

x = zip(x1,x2,x3)
A = np.array(x)
print A


[[ 1  0  0]
 [ 0  1  0]
 [ 0 -5  1]]


In [6]:
y1 = [1,0,0]
y2 = [0,2,-1]
y3 = [0,3,0]

y1_vector = np.array(y1)
y2_vector = np.array(y2)
y3_vector = np.array(y3)

y = zip(y1,y2,y3)
B = np.array(y)
print B

[[ 1  0  0]
 [ 0  2  3]
 [ 0 -1  0]]


In [8]:
n =A*B
print n

[[1 0 0]
 [0 2 0]
 [0 5 0]]


In [9]:
n1=A*0
print n1

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [11]:
##constains
y1_vector = np.array([1,-1,1])

In [13]:
y1 = [1,2,3,4]
y2 = [2,3,4,5]

y1_vector = np.array(y1)
y2_vector = np.array(y2)

y = zip(y1,y2)
B = np.array(y)
print B

[[1 2]
 [2 3]
 [3 4]
 [4 5]]


In [16]:
A = [[2, 3, 5], [-4, 2, 3], [0, 0, 0]]

In [19]:
A = Matrix(A)

In [20]:
A * A.nullspace()[0]

Matrix([
[0],
[0],
[0]])

In [21]:
A.nullspace()

[Matrix([
 [-1/16],
 [-13/8],
 [    1]])]