In [9]:
import sympy as sympy
import numpy as np
import matplotlib.pyplot as plt
from sympy import Matrix
from scipy import *

In [10]:
# Create a vector
myVector = np.array([1,2,3,4])

# Create a matrix
myMatrix = np.matrix(np.random.random((5,5)))

In [11]:
print myVector
print myMatrix

[1 2 3 4]
[[ 0.81971345  0.20156228  0.94911614  0.39725815  0.05228855]
 [ 0.82030957  0.46747943  0.47154835  0.25432763  0.38801827]
 [ 0.37566411  0.55502573  0.17190759  0.75482344  0.82576964]
 [ 0.22053465  0.14385348  0.80623656  0.50819365  0.29851977]
 [ 0.70287789  0.05090005  0.60044159  0.68926768  0.71067444]]


In [14]:
# Create a 2X2 identity matrix
np.eye(3, k=1)        

# Create a 2x2 identity matrix
np.mat(np.identity(2))         



matrix([[ 1.,  0.],
        [ 0.,  1.]])